In [43]:
import pandas as pd
import numpy as np
import Range_Model as rp # наша созданная модель

In [44]:
#Импортируем Датасеты тестовой и тренировочной выборки
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('df_hack_fineal_fillna.csv')

df_train['MEAS_DT'] = pd.to_datetime(df_train['MEAS_DT'], unit= 's')
df_train

,Unnamed: 0,MEAS_DT,Cu_oreth,Ni_oreth,Ore_mass,Mass_1,Mass_2,Dens_4,Mass_4,Vol_4,...,Cu_3.1T_max,Cu_3.1T_min,FM_3.2_A,Cu_3.2C_max,Cu_3.2C_min,Ni_3.2C_max,Ni_3.2C_min,Cu_3.2T_max,Cu_3.2T_min,Ni_rec
0,2,2024-01-01 00:30:00,2.5109,1.4355,840.0,1188.762573,698.350586,1.339792,707.198547,1548.09375,...,1.0,0.8,0.0,14.0,12.0,3.7,3.5,1.2,1.00,0.970170
1,3,2024-01-01 00:45:00,2.4765,1.3852,824.0,1151.888672,714.678101,1.342392,707.865540,1538.87500,...,1.0,0.8,0.0,14.0,12.0,3.7,3.5,1.2,1.00,0.968639
2,4,2024-01-01 01:00:00,2.3585,1.3368,0.0,1104.101318,730.190674,1.337608,700.935059,1545.18750,...,1.0,0.8,0.0,14.0,12.0,3.7,3.5,1.2,1.00,0.974205
3,5,2024-01-01 01:15:00,2.3672,1.3081,781.0,1077.806885,738.083862,1.336420,697.026794,1542.00000,...,1.0,0.8,0.0,14.0,12.0,3.7,3.5,1.2,1.00,0.973383
4,6,2024-01-01 01:30:00,2.4030,1.3266,992.0,1056.742554,737.300171,1.333465,690.764038,1541.68750,...,1.0,0.8,0.0,14.0,12.0,3.7,3.5,1.2,1.00,0.938520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25455,30331,2024-11-11 22:45:00,2.7133,1.4200,1231.0,1377.498413,766.228027,1.341972,707.754150,1540.31250,...,1.8,0.8,1.0,16.5,13.0,3.7,3.5,1.8,0.75,0.939579
25456,30332,2024-11-11 23:00:00,2.7582,1.5234,1149.5,1412.641235,769.619324,1.342853,709.036865,1538.21875,...,1.8,0.8,1.0,16.5,13.0,3.7,3.5,1.8,0.75,0.944490
25457,30333,2024-11-11 23:15:00,2.7487,1.5030,1210.5,1365.101562,785.184998,1.346513,718.652710,1543.53125,...,1.8,0.8,1.0,16.5,13.0,3.7,3.5,1.8,0.75,0.943409
25458,30334,2024-11-11 23:30:00,2.7067,1.5257,1389.5,1382.615723,788.089050,1.346020,716.409607,1540.90625,...,1.8,0.8,1.0,16.5,13.0,3.7,3.5,1.8,0.75,0.943442
25459,30335,2024-11-11 23:45:00,2.7335,1.5712,1370.0,1453.007324,786.615051,1.347941,716.809204,1532.50000,...,1.8,0.8,1.0,16.5,13.0,3.7,3.5,1.8,0.75,0.945416

In [45]:
# Получаем значения даты и времени из тестовый выборки, 
# чтобы в соответствии с ними получить признаки из тренировочной выборки для их использования при тестировании нашей модели


feats_name = ['MEAS_DT', 
              'Ni_1.1C', 'Ni_1.2C',     # Признаки, по которым будут строиться интервалы 
              'Cu_1.1C', 'Cu_1.2C',
              'Cu_2.1T', 'Cu_2.2T',
              'Cu_3.1T', 'Cu_3.2T',
              'Ni_4.1T', 'Ni_4.2T',
              'Ni_4.1C', 'Ni_4.2C',
              'Ni_5.1T', 'Ni_5.2T',
              'Ni_5.1C', 'Ni_5.2C',
              'Ni_6.1T', 'Ni_6.2T',
              'Ni_6.1C', 'Ni_6.2C']

# df_train['MEAS_DT'].isin(test_datetime).sum()

feats = df_train[df_train['MEAS_DT'].isin(df_test['MEAS_DT'])][feats_name]

# df_test = df_test.loc[df_test['MEAS_DT'].isin(feats['MEAS_DT'])]

# # print(df_train['Ni_1.1C'][df_train['MEAS_DT'].index (df_test['MEAS_DT'][0])])
feats
# feats_time = feats.MEAS_DT
# feats_time

,MEAS_DT,Ni_1.1C,Ni_1.2C,Cu_1.1C,Cu_1.2C,Cu_2.1T,Cu_2.2T,Cu_3.1T,Cu_3.2T,Ni_4.1T,...,Ni_4.1C,Ni_4.2C,Ni_5.1T,Ni_5.2T,Ni_5.1C,Ni_5.2C,Ni_6.1T,Ni_6.2T,Ni_6.1C,Ni_6.2C
1500,2024-01-19 12:15:00,2.5762,2.5430,4.8183,4.3336,0.4399,0.3877,2.0676,1.1963,0.6883,...,4.2114,4.3147,0.6755,0.6672,6.2148,6.4402,1.1765,1.0752,8.8743,9.1069
1501,2024-01-19 12:30:00,2.5744,2.5648,4.8403,4.3226,0.4411,0.3882,1.8965,1.1303,0.6944,...,4.2360,4.2632,0.6795,0.6582,6.2328,6.2411,1.1861,1.0185,8.9227,9.0740
1502,2024-01-19 12:45:00,2.5533,2.5557,4.8434,4.3387,0.4395,0.3898,1.4330,1.1070,0.6787,...,4.1946,4.2512,0.6853,0.6529,6.2165,6.3268,1.1878,1.0600,8.9521,9.0745
1503,2024-01-19 13:00:00,2.6247,2.5647,4.8831,4.3607,0.4394,0.3899,1.0288,1.0598,0.7013,...,4.2584,4.3323,0.6754,0.6450,6.1857,6.3747,1.2009,1.0595,8.8664,9.0688
1504,2024-01-19 13:15:00,2.5052,2.6089,4.9744,4.4420,0.4423,0.3918,0.9042,1.0038,0.6921,...,4.1174,4.2574,0.6693,0.6554,6.2420,6.4812,1.1918,1.0414,8.9041,9.0818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24892,2024-11-05 17:15:00,2.9512,3.3834,4.7544,4.8921,0.3683,0.5286,1.4115,1.4988,0.7162,...,4.6275,4.3182,0.6141,0.6592,6.4981,6.5856,1.6368,1.3934,8.8970,8.9080
24893,2024-11-05 17:30:00,2.9725,3.4019,4.6133,4.8583,0.3687,0.5305,1.3635,1.4586,0.7148,...,4.6653,4.3139,0.6028,0.6446,6.5864,6.4582,1.6459,1.3594,8.8497,8.8989
24894,2024-11-05 17:45:00,3.0477,3.3728,4.8160,4.6395,0.3695,0.5267,1.3009,1.3842,0.7149,...,4.6139,4.3246,0.6127,0.6515,6.4492,6.3936,1.6369,1.3443,8.8490,8.9010
24895,2024-11-05 18:15:00,2.8396,3.2740,4.4311,4.3446,0.3741,0.5064,1.3040,1.2819,0.7032,...,4.6489,4.2768,0.6099,0.6504,6.5859,6.4258,1.6412,1.3651,8.7280,8.8520
24896,2024-11-05 18:30:00,2.7479,3.2749,4.2417,4.2724,0.3780,0.4971,1.2853,1.3132,0.7067,...,4.6024,4.2750,0.6120,0.6540,6.3607,6.3893,1.6526,1.3534,8.7439,8.8343

In [46]:
import math
dict_feats = {'Ni_1.1C': (0.1,	3, 0.2,	0.2),
              'Ni_1.2C': (0.1,	3, 0.2,	0.2),    
              'Cu_1.1C': (0.1,	5, 0.1,	0.2), 
              'Cu_1.2C': (0.1,	5, 0.1,	0.2),
              'Cu_2.1T': (0.01,	1, 0.2,	0.2),
              'Cu_2.2T': (0.01,	1, 0.2,	0.2),
              'Cu_3.1T': (0.05,	1, 0.3,	0.1), 
              'Cu_3.2T': (0.05,	1, 0.3,	0.1),
              'Ni_4.1T': (0.01,	2, 0.1,	0.2),
              'Ni_4.2T': (0.01,	2, 0.1,	0.2),
              'Ni_4.1C': (0.05,	4, 0.15,0.2),
              'Ni_4.2C': (0.05,	4, 0.15,0.2),
              'Ni_5.1T': (0.01,	2, 0.1,	0.2),
              'Ni_5.2T': (0.01,	2, 0.1,	0.2),
              'Ni_5.1C': (0.05,	4, 0.1, 0.2),
              'Ni_5.2C': (0.05,	4, 0.1, 0.2),
              'Ni_6.1T': (0.01,	1, 0.15, 0.01),
              'Ni_6.2T': (0.01,	1, 0.15, 0.01),
              'Ni_6.1C': (0.05,	3, 0.1, 0.01),
              'Ni_6.2C': (0.05, 3, 0.1, 0.01)}

for feat_name in feats_name[1:]:
    
    feat = df_train[feat_name]
    tracker = rp.AdaptiveIntervalTracker(
        granularity=dict_feats[feat_name][0], tolerance=dict_feats[feat_name][2], lock_threshold=8, max_buffer=dict_feats[feat_name][1], p=dict_feats[feat_name][3])

    data_stream = feat
    order = math.floor(math.log10(abs(dict_feats[feat_name][0])))
    current_interval_min = []
    current_interval_max = []
    for value in data_stream:
        current_interval = tracker.update_interval(value)
        current_interval_min.append(round(current_interval[0], abs(order)))
        current_interval_max.append(round(current_interval[1], abs(order)))

    df_train[feat_name + '_min'] = current_interval_min
    df_train[feat_name + '_max'] = current_interval_max
df_test["MEAS_DT"] = pd.to_datetime(df_test["MEAS_DT"])
df_train["MEAS_DT"] = pd.to_datetime(df_train["MEAS_DT"])
columns_to_merge = []
for i in feats_name[1:]:
    columns_to_merge.append(i + '_min')
    columns_to_merge.append(i + '_max')
merged_df = df_test.merge(df_train[["MEAS_DT"] + columns_to_merge], on="MEAS_DT", how="left", suffixes=("_old", ""))

# Обновление значений в df2 из merged_df
for col in columns_to_merge:
    merged_df[col] = merged_df[col].fillna(merged_df[f"{col}_old"])

# Удаление временных столбцов
merged_df = merged_df.drop(columns=[f"{col}_old" for col in columns_to_merge])
merged_df

,MEAS_DT,Ni_1.1C_min,Ni_1.1C_max,Ni_1.2C_min,Ni_1.2C_max,Cu_1.1C_min,Cu_1.1C_max,Cu_1.2C_min,Cu_1.2C_max,Cu_2.1T_min,...,Ni_5.2C_min,Ni_5.2C_max,Ni_6.1T_min,Ni_6.1T_max,Ni_6.2T_min,Ni_6.2T_max,Ni_6.1C_min,Ni_6.1C_max,Ni_6.2C_min,Ni_6.2C_max
0,2024-01-19 12:15:00,2.5,3.1,2.4,3.0,4.7,5.1,4.6,5.0,0.40,...,6.15,6.80,1.11,1.29,0.97,1.13,8.40,9.30,8.7,9.6
1,2024-01-19 12:30:00,2.5,3.1,2.4,3.0,4.7,5.1,4.6,5.0,0.40,...,6.15,6.80,1.11,1.29,0.97,1.13,8.40,9.30,8.7,9.6
2,2024-01-19 12:45:00,2.5,3.1,2.3,2.9,4.7,5.1,4.6,5.0,0.40,...,6.15,6.80,1.11,1.29,0.98,1.14,8.40,9.30,8.7,9.6
3,2024-01-19 13:00:00,2.5,3.1,2.3,2.9,4.7,5.1,4.6,5.0,0.40,...,6.15,6.80,1.11,1.29,0.98,1.14,8.40,9.30,8.7,9.6
4,2024-01-19 13:15:00,2.5,3.1,2.3,2.9,4.7,5.1,4.6,5.0,0.40,...,6.15,6.80,1.10,1.28,0.98,1.14,8.40,9.30,8.7,9.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6735,2024-11-05 17:30:00,2.6,3.2,3.1,3.7,4.4,4.8,4.3,4.7,0.33,...,6.35,7.05,1.51,1.75,1.26,1.46,8.45,9.35,8.7,9.6
6736,2024-11-05 17:45:00,2.6,3.2,3.1,3.7,4.5,4.9,4.3,4.7,0.33,...,6.15,6.75,1.51,1.75,1.26,1.46,8.45,9.35,8.7,9.6
6737,2024-11-05 18:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6738,2024-11-05 18:15:00,2.6,3.2,3.0,3.6,4.5,4.9,4.3,4.7,0.33,...,6.15,6.75,1.51,1.75,1.26,1.46,8.45,9.35,8.7,9.6
6739,2024-11-05 18:30:00,2.6,3.2,3.0,3.6,4.5,4.9,4.3,4.7,0.34,...,6.15,6.75,1.51,1.75,1.26,1.46,8.45,9.35,8.7,9.6

In [47]:
merged_df.to_csv('test1.csv', index=False)